# Site settings
title: ikr's primitive mind eruptions
email: ikr@ikr.su
description: > # this means to ignore newlines until "baseurl:"
  Hey there! My name is Ivan. I'm a constant learner, who loves building smart and well-crafted
  software systems that are a joy to use and maintain. Beside computers and software, I love life in
  general. I like feeling happy, and talking to kind, positive people.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ikr.su" # the base hostname & protocol for your site
twitter_username: ikr
github_username:  ikr

# Build settings
markdown: kramdown
